### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by dkoding** [crashinvaders/gdx-vfx#20]
Could some information about the performance and configuration of the different bundled effects be added? I find some effects I like and try to tweak the parameters, but I'm somewhat in the dark regarding performance impact. Especially the Bloom effect is nice but it halves my framerate from 60 to 30 (could it be improved? https://stackoverflow.com/questions/98359/fastest-gaussian-blur-implementation).

**Comment by metaphore** [comment]
Hi @dkoding 
Unfortunately, the implemented effects are not the best in class and have mostly been adapted from the original https://github.com/manuelbua/libgdx-contribs/tree/master/postprocessing project, which is quite old.

At this point, I don't actively maintain this project, and I'm afraid I cannot invest the time in improving it. if you are willing to make a performance comparison chart or implement a faster version of existing effects, you're very welcome to make a PR.
