### ISSUE TITLE
duplicate entry: gdxvfx/shaders/old-tv.frag

### ISSUE THREAD

**Issue by littleariel** [crashinvaders/gdx-vfx#24]
After including this library into our project, our build process fails with the following error:

```* What went wrong:
Execution failed for task ':wear:mergeExtDexStandaloneDebug'.
> Could not resolve all files for configuration ':wear:standaloneDebugRuntimeClasspath'.
   > Failed to transform gdx-vfx-effects-0.5.1.jar (com.crashinvaders.vfx:gdx-vfx-effects:0.5.1) to match attributes {artifactType=android-dex, asm-transformed-variant=standaloneDebug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=24, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AsmClassesTransform: /Users/arielvardi/.gradle/caches/transforms-3/43c8bf1c6fd0f5c049278f813773d04e/transformed/jetified-gdx-vfx-effects-0.5.1.jar.
         > duplicate entry: gdxvfx/shaders/old-tv.frag
```

The library was included with the following:

```
    implementation 'com.crashinvaders.vfx:gdx-vfx-core:0.5.1'
    implementation 'com.crashinvaders.vfx:gdx-vfx-effects:0.5.1'    // Optional, if you need standard filter/effects.
```

Note that if the `-effects` one is not included, the project builds okay... but obviously is missing all the effects we'd want to use.

**Comment by metaphore** [comment]
I just generated a blank project using [`gdx-liftoff`](https://github.com/tommyettinger/gdx-liftoff) that includes both `gdx-vfx-core` and `gdx-vfx-effects` wth sample code from [the readme](https://github.com/crashinvaders/gdx-vfx#2-sample-code) of GDX-VFX. It builds and works with no issues using the default gradle configuration for both LWJGL3 and Android (API 32) targets. Please try calling `./gradlew android:assemble` from the example project [vfx-test-230823.zip](https://github.com/crashinvaders/gdx-vfx/files/12422793/vfx-test-230823.zip)

As for the error you're having, my guess would be you have either duplicate dependencies (`gdx-vfx-effects`) or you might have this file (`gdxvfx/shaders/old-tv.frag`) previously copied to your assets directory.

It's hard to guess anything beyond that without looking at your gradle config.

**Comment by QboiDev** [comment]
Same issue, but with Architectury Loom
It has duplicates can confirm:
![image](https://github.com/crashinvaders/gdx-vfx/assets/30625109/58c960f4-01de-4a12-bd32-ab28ae058f98)

**Comment by QboiDev** [comment]
Using 0.5.0 here, same with 0.5.4

**Comment by QboiDev** [comment]
(Copying would be spammy)
![image](https://github.com/crashinvaders/gdx-vfx/assets/30625109/9ef61ea7-8afe-4f6a-90a3-34c11de65bd4)
