### ISSUE TITLE
v0.5.2 build on Maven Central is broken

### ISSUE THREAD

**Issue by rafaskb** [crashinvaders/gdx-vfx#25]
I was just updating gdx-vfx from 0.5.1 to 0.5.2 and suddenly the IDE couldn't find any of the imports for the various classes of the library, but Gradle kept saying the dependency had been downloaded just fine. So I went to Sonatype (https://central.sonatype.com/artifact/com.crashinvaders.vfx/gdx-vfx-core/versions) and downloaded the jars for both 0.5.1 and 0.5.2 to see what they had inside, and to my surprise gdx-vfx-core-0.5.2.jar is empty! It has only 261 bytes (as opposed to 49.5 KB from gdx-vfx-core-0.5.1.jar), and just a META-INF folder inside the jar.

I see there were some commits related to gradle publishing, so my guess is that something went wrong in the process.

**Comment by metaphore** [comment]
Thanks for reporting this!
My bad, I should have checked as it happened before.
Please try updating to the fresh `0.5.3`

**Comment by rafaskb** [comment]
Works perfectly! Thanks for fixing it so quickly 😁
