### ISSUE TITLE
Different resolutions for different passes

### ISSUE THREAD

**Issue by b005t3r** [crashinvaders/gdx-vfx#27]
I want to first render my project to a 320x240 fbo, then render it to a 3x larger fbo using a custom CRT effect. Is there an easy way of doing that, ideally without adding any unnecessary texture copying steps? I went through the docs and build-in shaders, but didn't find anything like that.

**Comment by metaphore** [comment]
For that case, I don't you get much benefit from using this project. It does fine with a basic single pass flow, but if you want something more complected than that, I'd suggest you go with your own implementation (especially if you know what you're doing and how to make it work in OpenGL). This project is quite old and I'd say have some questionable solutions, like totally unnecessary custom FBO wrapper, that I found through years only overcomplicates things...

**Comment by b005t3r** [comment]
OK, thanks for the reply. I'll try to cook something on my own :)

**Comment by metaphore** [comment]
Sure! Best of luck!
