### ISSUE TITLE
[EFFECT REQUEST] Earthquake Screen Shake

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-vfx#4]
A screen shake effect would be a welcome addition. This is a commonly used effect when there are explosions on screen or if a character falls onto the ground very hard. Please see an example here: https://www.shadertoy.com/view/wsBXWW

I would love to write a PR, but unfortunately I'm in the middle of a project right now. Thanks for your consideration!

**Comment by metaphore** [comment]
Not sure about this one, for such effect it's always better to just shake the camera, will save some GPU resources.

**Comment by arthurtemple** [comment]
Moving the camera indeed looks like the cleanest path.

Maybe you can work this out from the example here https://github.com/spookygames/gdx-gfx/blob/master/src/test/java/net/spookygames/gdx/gfx/demo/fx/ScreenShake.java? (all kudos go to [this article by Jonny Morrill](https://jonny.morrill.me/en/blog/gamedev-how-to-implement-a-camera-shake-effect)).

**Comment by metaphore** [comment]
Wow, I didn't know that project existed. I was in one letter from stilling its name :)

**Comment by metaphore** [comment]
Sorry, due to the previous conversation and the fact I'm trying to keep the number of the built-in effects down to the only essential ones, I'm gonna reject this one. I still need to revisit the existing effects and clean them up/remove some, but that's for the next release I guess.
