### ISSUE TITLE
[EFFECT REQUEST] Underwater Effect

### ISSUE THREAD

**Issue by raeleus** [crashinvaders/gdx-vfx#5]
An underwater effect would make a great addition for water based games/levels. It can also be manipulated to simulate a drunken or poisoned state. Please see an example here: https://www.shadertoy.com/view/4ltSDB

I would love to write a PR, but unfortunately I'm in the middle of a project right now. Thanks for your consideration!

**Comment by metaphore** [comment]
Looks pretty simple, will consider adopting this one when I finish the big refactoring I'm in right now. Thanks!

**Comment by payne911** [comment]
How about adding (a more aggressive) Ripples effect, too? :o
